/**
 * Script de migration : importe les données mock dans Sanity.
 *
 * Usage :
 *   node scripts/migrate.mjs
 *
 * Prérequis :
 *   - npm install dans sanity-studio/
 *   - Avoir un token d'écriture dans SANITY_TOKEN
 *   - Remplir PROJECT_ID et DATASET ci-dessous
 *
 * Obtenir un token : https://www.sanity.io/manage → projet → API → Tokens → Add API token (Editor)
 */

import { createClient } from '@sanity/client'

// ⚠️  À remplir avant de lancer le script
const PROJECT_ID   = 'dqwhxx3m'
const DATASET      = 'production'
const SANITY_TOKEN = process.env.SANITY_TOKEN ?? 'VOTRE_TOKEN_ICI'

const client = createClient({
  projectId: PROJECT_ID,
  dataset: DATASET,
  apiVersion: '2024-01-01',
  token: SANITY_TOKEN,
  useCdn: false,
})

// ─── Données mock ────────────────────────────────────────────────────────────

const events = [
  { id: '1', title: "CAF'DATA #12 : IA – Par où commencer pour ne pas se planter ?", date: '2025-07-09', location: "CODA – École d'informatique, Orléans", type: 'Atelier', summary: "Les clés pour construire une stratégie IA concrète et adaptée à votre organisation.", link: 'https://ia-loirevalley.fr/agenda/cafdata-12-ia-par-ou-commencer-pour-ne-pas-se-planter/' },
  { id: '2', title: "Journée Expert – L'IA au service des territoires", date: '2025-06-24', location: 'Centre de Création Contemporaine Olivier Debré (CCCOD), Tours', type: 'Conférence', summary: "Une journée complète pour explorer comment l'IA peut transformer les services publics.", link: 'https://ia-loirevalley.fr/agenda/journee-expert-lia-au-service-des-territoires/' },
  { id: '3', title: "Festival Re{Dé}connecte – Arts hybrides & cultures numériques", date: '2025-06-17', location: 'Centre-Val de Loire', type: 'Conférence', summary: "Festival de 5 jours autour des arts hybrides, des cultures numériques et de l'IA.", link: 'https://ia-loirevalley.fr/agenda/festival-redeconnecte-arts-hybrides-cultures-numeriques/' },
  { id: '4', title: "Intelligence Artificielle : Mythes et Réalités", date: '2025-06-11', location: 'CRIJ Centre-Val de Loire', type: 'Conférence', summary: "Une conférence grand public pour démêler le vrai du faux sur l'IA.", link: 'https://ia-loirevalley.fr/agenda/intelligence-artificielle-mythes-et-realites/' },
  { id: '5', title: "Tournée Régionale – Place du Numérique", date: '2025-05-06', location: 'Centre-Val de Loire (itinérant)', type: 'Conférence', summary: "Événement grand public et gratuit sur les métiers et enjeux du numérique.", link: 'https://ia-loirevalley.fr/agenda/tournee-regionale-place-du-numerique/' },
  { id: '6', title: "French Tech Tour Centre-Val de Loire", date: '2025-04-29', location: 'Centre-Val de Loire (itinérant)', type: 'Networking', summary: "Mise à l'honneur des startups régionales et du développement innovant.", link: 'https://ia-loirevalley.fr/agenda/french-tech-tour-centre-val-de-loire-en-partenariat-avec-digital-loire-valley/' },
  { id: '7', title: "Journée « L'IA au service du Droit »", date: '2025-04-09', location: 'Centre-Val de Loire', type: 'Conférence', summary: "L'intelligence artificielle transforme le monde du droit.", link: 'https://ia-loirevalley.fr/agenda/journee-lia-au-service-du-droit/' },
  { id: '8', title: "Les Rencontres de la donnée", date: '2025-04-03', location: 'Orléans', type: 'Networking', summary: "Matinée de networking et d'échanges autour des enjeux de la donnée.", link: 'https://ia-loirevalley.fr/agenda/les-rencontres-de-la-donnee-le-3-avril-a-orleans/' },
  { id: '9', title: "CAF'DATA #11 : Vos données ont de la valeur… et des prédateurs !", date: '2025-04-02', location: "LAB'O Village By CA, Orléans", type: 'Atelier', summary: "Sécurité numérique et économique pour professionnels.", link: 'https://ia-loirevalley.fr/agenda/cafdata-11-vos-donnees-ont-de-la-valeur-et-des-predateurs/' },
  { id: '10', title: "L'IA va-t-elle sauver le monde ?", date: '2025-03-27', location: "Amphithéâtre Jousse, Faculté de Droit", type: 'Conférence', summary: "« Tribunal pour les Générations Futures » organisé par Usbek & Rica.", link: 'https://ia-loirevalley.fr/agenda/lia-va-t-elle-sauver-le-monde/' },
]

const experts = [
  { id: '1', name: 'CadrIA', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CadrIA', specialty: "Assistants d'IA Professionnels Métiers", location: 'Bourges', address: '1 rue Michel Servet, 18000 Bourges', sectors: ['Services', 'Tech'], expertise: ['IA professionnelle', 'Assistants IA', 'Automatisation métier'], level: 'Accompagnement', description: "CadrIA développe des assistants d'intelligence artificielle professionnels adaptés aux métiers.", website: 'https://cadria.fr', email: 'stephane@cadria.fr' },
  { id: '2', name: 'Croissances', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Croissances', specialty: "Formation et Conseil sur l'IA", location: 'Blois', address: "4 impasse de l'Orée du Bois, 41000 Blois", sectors: ['Formation', 'Services'], expertise: ['Formation IA', 'Conseil', 'Conduite du changement'], level: 'Formation', description: "Croissances est l'activateur de vos changements : formation et conseil sur l'IA.", website: 'https://www.croissances.net', email: 'sophie.yasmine@croissances.net' },
  { id: '3', name: 'HQ Logic', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=HQLogic', specialty: 'Agents IA autonomes & Automatisation', location: 'Tours', address: "Allée de Mazières, 37390 Notre-Dame-d'Oé", sectors: ['Tech', 'Services'], expertise: ['Agents IA', 'Workflows automatisés', 'Solutions sur-mesure'], level: 'Développement', description: 'HQ Logic développe des agents IA autonomes et des workflows automatisés.', website: 'https://hq-logic.com/', email: 'quentin.gasnier@hq-logic.com' },
  { id: '4', name: 'Télétravail Quadralinda', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Quadralinda', specialty: 'IA générative & Télétravail', location: 'Tours', address: '8 Rue de Balzac, 37000 Tours', sectors: ['Services', 'Communication'], expertise: ['IA générative', 'Télétravail', 'Productivité'], level: 'Accompagnement', description: "Spécialiste de l'IA générative appliquée aux contextes de télétravail.", website: 'https://teletravailquadralinda.com/', email: 'contact@teletravailquadralinda.com' },
  { id: '5', name: "LAB'IA Loire Valley", avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LABIALoireValley', specialty: 'Centre de Ressources partagées Data & IA', location: 'Orléans', address: '1 Avenue du champ de mars, 45074 Orléans', sectors: ['Tech', 'Services', 'Collectivités'], expertise: ['Centre de ressources', 'Données', 'Mutualisation'], level: 'Conseil', description: "Le LAB'IA Loire Valley est un centre de ressources partagées autour de la donnée et de l'IA.", website: 'https://www.labia-loirevalley.fr/', email: 'corinne.neau@tech-orleans.fr' },
  { id: '6', name: "CODA – École Supérieure d'Informatique", avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CODASchool', specialty: "Enseignement supérieur en informatique et IA", location: 'Orléans', address: "24 Rue Jeanne d'Arc, 45000 Orléans", sectors: ['Formation', 'Tech'], expertise: ['Formation initiale', 'Informatique', 'IA appliquée'], level: 'Formation', description: "École supérieure d'informatique à Orléans.", website: 'https://www.coda.school/', email: 'clement@coda.school' },
  { id: '7', name: 'Ontomantics', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ontomantics', specialty: 'Digitalisation No Code et IA', location: 'Orléans', address: '959 rue de la Bergeresse, 45160 Olivet', sectors: ['Tech', 'Services'], expertise: ['No Code', 'Digitalisation', 'IA appliquée'], level: 'Développement', description: "Ontomantics accompagne les entreprises dans leur digitalisation grâce aux outils No Code et IA.", website: 'https://www.ontomantics.com/', email: 'emilie.baumann@ontomantics.com' },
  { id: '8', name: 'TerraQuant', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TerraQuant', specialty: 'Conseil en Data & IA', location: 'Orléans', address: 'La Râpe, 45000 Orléans', sectors: ['Tech', 'Services'], expertise: ['Data science', 'Machine learning', 'Conseil stratégique'], level: 'Conseil', description: 'Cabinet de conseil en Data et IA.', website: 'https://terraquant.fr/', email: 'contact@terraquant.fr' },
  { id: '9', name: 'Heko Lab', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=HekoLab', specialty: 'Solutions web et mobile fiables et évolutives', location: 'Tours', address: '1 rue de Bouilly, 37000 Tours', sectors: ['Tech', 'Services'], expertise: ['Développement web', 'Mobile', 'IA intégrée'], level: 'Développement', description: 'Heko Lab développe des solutions web et mobile intégrant les dernières avancées en IA.', website: 'https://www.heko-lab.com/', email: 'andrea.maugars@heko-lab.com' },
  { id: '10', name: 'PC4U', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PC4U', specialty: 'Services informatiques & IA souveraine', location: 'Tours', address: 'rue Agnès Sorel, 37310 Dolus-Le-Sec', sectors: ['Tech', 'Services'], expertise: ['Informatique', 'IA souveraine', 'Auto-hébergement'], level: 'Développement', description: "PC4U propose des services informatiques et des solutions d'IA souveraine.", website: 'https://pc4you.fr/solution-box-ia-souveraine-auto-hebergee/', email: 'helene.pc4you@gmail.com' },
  { id: '11', name: 'AMI-IA', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AMIIA', specialty: "Maîtrise d'oeuvre en Intelligence Artificielle", location: 'Tours', address: 'rue du Docteur Trousseau, 37540 Saint-Cyr-sur-Loire', sectors: ['Tech', 'Services'], expertise: ["Maîtrise d'oeuvre IA", 'Intégration', 'Architecture IA'], level: 'Développement', description: "Agence de Maîtrise d'Informatique et d'Intelligence Artificielle.", website: 'https://www.ami-ia.fr', email: 'francois.toudross@ami-ia.fr' },
  { id: '12', name: 'Iphaïstos', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Iphaistos', specialty: 'Technologie au service de la performance industrielle', location: 'Blois', address: 'route de Selles, 41130 Gièvres', sectors: ['Industrie', 'Tech'], expertise: ['Performance industrielle', 'Automatisation', 'IA industrielle'], level: 'Développement', description: "Iphaïstos met la technologie et l'IA au service de la performance industrielle.", website: 'http://www.iphaistos.com', email: 'patrice.ballereau@iphaistos.com' },
  { id: '13', name: 'PRISME – Axe Images Vision', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PRISMEImages', specialty: "Vision par ordinateur & IA image", location: 'Orléans', address: '8 Rue Léonard de Vinci, 45072 Orléans', sectors: ['Recherche', 'Tech'], expertise: ['Vision par ordinateur', "Traitement d'images", 'Deep learning'], level: 'Conseil', description: "Axe de recherche du laboratoire PRISME spécialisé en vision par ordinateur.", website: 'http://www.aladine-chetouani.com', email: 'aladine.chetouani@univ-orleans.fr' },
  { id: '14', name: 'ICOA – Institut de Chimie Organique', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ICOA', specialty: 'IA appliquée à la chimie et aux sciences', location: 'Orléans', address: 'Rue de Chartres, 45100 Orléans', sectors: ['Recherche', 'Industrie'], expertise: ['Chimie computationnelle', 'IA scientifique', 'Modélisation'], level: 'Conseil', description: "L'ICOA développe des approches IA pour la recherche en chimie.", website: 'https://www.icoa.fr/fr/bonnet', email: 'pascal.bonnet@univ-orleans.fr' },
  { id: '15', name: 'Mission Internet', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MissionInternet', specialty: 'SEO & Data pour le référencement naturel', location: 'Orléans', address: '106 Avenue Dauphine, 45100 Orléans', sectors: ['Marketing', 'Tech'], expertise: ['SEO', 'Analyse de logs', 'Data marketing'], level: 'Accompagnement', description: "Agence web spécialisée dans le référencement naturel et la data.", website: 'https://www.mission-internet.fr', email: 'guillaume@mission-internet.fr' },
  { id: '16', name: 'TECHNORD France', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TECHNORD', specialty: 'Intégration de projets industriels & IA', location: 'Orléans', address: '55 rue Edouard Branly, 45800 Saint-Jean-de-Braye', sectors: ['Industrie', 'Énergie'], expertise: ['Industrie 4.0', 'Automatisation', 'Intégration industrielle'], level: 'Développement', description: "Groupe industriel spécialisé dans l'intégration de projets industriels.", website: 'https://www.technord.com/process-improvement-4-0/', email: 'f.durand@technord.com' },
  { id: '17', name: 'Clément Lelièvre', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ClementLelievre', specialty: 'Data Science & Python', location: 'Blois', address: '14 rue Gustave Marc, 41150 Onzain', sectors: ['Tech', 'Services'], expertise: ['Data science', 'Python', 'Machine learning'], level: 'Développement', description: "Auto-entrepreneur spécialisé en data science et développement Python.", website: 'https://www.malt.fr/profile/python', email: 'clement.datascience@gmail.com' },
  { id: '18', name: 'CETU ILIAD3', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ILIAD3', specialty: "Centre d'Expertise et de Transfert Universitaire", location: 'Tours', address: '64 avenue Jean Portalis, 37200 Tours', sectors: ['Recherche', 'Formation'], expertise: ['Transfert technologique', 'Innovation', 'Recherche appliquée'], level: 'Conseil', description: "Centre d'Expertise et de Transfert Universitaire de l'Université de Tours.", website: 'https://iliad3.univ-tours.fr', email: 'iliad3@univ-tours.fr' },
  { id: '19', name: 'DCID – Data Science Consulting', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DCID', specialty: 'Conseil, expertise et formation en Data Science', location: 'Orléans', address: 'boulevard Duhamel du Monceau, 45160 Olivet', sectors: ['Tech', 'Services'], expertise: ['Data science', 'Big data', 'Formation data'], level: 'Conseil', description: "Société de conseil, d'expertise et de formation en data science.", website: 'http://www.dcid-consulting.fr', email: 'contact@dcid-consulting.fr' },
  { id: '20', name: 'Polytech Tours', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PolytechTours', specialty: "École d'ingénieurs – Informatique & IA", location: 'Tours', address: '64 Avenue Jean Portalis, 37200 Tours', sectors: ['Formation', 'Recherche'], expertise: ["Formation ingénieurs", 'Informatique', 'IA'], level: 'Formation', description: "École d'ingénieurs de l'Université de Tours.", website: 'https://polytech.univ-tours.fr/', email: 'polytech@univ-tours.fr' },
  { id: '21', name: 'Laboratoire LIFO', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LIFO', specialty: 'Informatique fondamentale & IA', location: 'Orléans', address: 'Rue Léonard de Vinci, 45067 Orléans', sectors: ['Recherche', 'Tech'], expertise: ['Algorithmique', 'IA fondamentale', 'Optimisation'], level: 'Conseil', description: "Laboratoire d'Informatique Fondamentale d'Orléans.", website: 'https://www.univ-orleans.fr/lifo/', email: 'contact.lifo@listes.univ-orleans.fr' },
  { id: '22', name: 'Institut Denis Poisson', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DenisPoisson', specialty: 'Mathématiques & IA', location: 'Orléans', address: 'Rue de Chartres, 45067 Orléans', sectors: ['Recherche'], expertise: ['Mathématiques appliquées', 'Modélisation', 'IA mathématique'], level: 'Conseil', description: "Institut de mathématiques de l'Université d'Orléans.", website: 'https://www.idpoisson.fr/', email: 'bruno.galerne@univ-orleans.fr' },
  { id: '23', name: 'Laboratoire LIFAT', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LIFAT', specialty: "Informatique & IA fondamentale – Université Tours", location: 'Tours', address: '64 avenue Portalis, 37200 Tours', sectors: ['Recherche', 'Tech'], expertise: ['IA fondamentale', 'Apprentissage automatique', 'Représentation des connaissances'], level: 'Conseil', description: "Laboratoire d'Informatique Fondamentale et Appliquée de Tours.", website: 'https://lifat.univ-tours.fr/', email: 'direction.lifat@univ-tours.fr' },
  { id: '24', name: 'Laboratoire PRISME', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PRISME', specialty: 'Productique, Robotique, Instrumentation & IA', location: 'Orléans', address: '8 rue Léonard de Vinci, 45072 Orléans', sectors: ['Recherche', 'Industrie'], expertise: ['Robotique', 'Vision industrielle', 'IA embarquée'], level: 'Conseil', description: "Laboratoire pluridisciplinaire de l'Université d'Orléans.", website: 'https://www.univ-orleans.fr/fr/prisme', email: 'directeur.prisme@univ-orleans.fr' },
  { id: '25', name: 'GIP RECIA', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=GPRECIA', specialty: 'Digital PME & Services numériques', location: 'Orléans', address: '151 rue de la Juine, 45160 Olivet', sectors: ['Collectivités', 'Tech'], expertise: ['Numérique éducatif', 'Digital PME', 'Services numériques'], level: 'Accompagnement', description: "GIP RECIA accompagne les PME et collectivités dans leur transformation numérique.", website: 'https://ledigitalpme.fr', email: 'contact@recia.fr' },
  { id: '26', name: 'AgreenTech Valley', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AgreenTech', specialty: 'Cluster végétal numérique & IA agricole', location: 'Orléans', address: '3 Rue Charles Sadron, 45100 Orléans', sectors: ['Agriculture', 'Tech'], expertise: ['AgTech', 'IA agricole', 'Données végétales'], level: 'Conseil', description: "Cluster spécialisé dans le numérique et l'IA appliqués au secteur végétal.", website: 'https://www.agreentechvalley.fr/', email: 'muriel.doucet@agreentechvalley.fr' },
  { id: '27', name: 'CRESITT Industrie', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CRESITT', specialty: 'Électronique & IA industrielle', location: 'Orléans', address: 'Avenue du champ de mars, 45100 Orléans', sectors: ['Industrie', 'Tech'], expertise: ['Électronique', 'Systèmes embarqués', 'IA industrielle'], level: 'Développement', description: "Structure experte en électronique et systèmes embarqués.", website: 'https://cresitt.com/', email: 'elisabeth.patouillard@cresitt.com' },
  { id: '28', name: 'CNAM Centre-Val de Loire', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CNAMOrléans', specialty: 'Formation professionnelle continue & IA', location: 'Orléans', address: '21B Rue Eugène Vignat, 45000 Orléans', sectors: ['Formation', 'Tech'], expertise: ['Formation continue', 'Certification', 'Numérique'], level: 'Formation', description: "Conservatoire National des Arts et Métiers de la région.", website: 'https://www.cnam-centre.fr/', email: 'karine.lefrancois@lecnam.net' },
  { id: '29', name: 'Nextino', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nextino', specialty: 'Programmes informatiques & IA', location: 'Orléans', address: '1 Avenue du champ de mars, 45074 Orléans', sectors: ['Tech', 'Services'], expertise: ['Développement logiciel', 'IA', 'Innovation'], level: 'Développement', description: "Nextino développe des programmes informatiques innovants.", website: 'http://www.nextino.eu' },
  { id: '30', name: 'Lycée Henri Brisson', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LyceeHenriBrisson', specialty: 'Licence Informatique & formation numérique', location: 'Vierzon', address: '25 Avenue Henri Brisson, 18100 Vierzon', sectors: ['Formation', 'Tech'], expertise: ['Informatique', 'Formation initiale', 'Numérique'], level: 'Formation', description: "Lycée de Vierzon proposant une filière Licence en informatique.", website: 'https://lycee-henribrisson.com/filiere/licence-informatique-generale/', email: 'karine.lefrancois@lecnam.net' },
  { id: '31', name: 'CESI', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CESIOrléans', specialty: "École d'ingénieurs & formation IA", location: 'Orléans', address: '1 Allée du Titane, 45100 Orléans', sectors: ['Formation', 'Tech'], expertise: ["Formation ingénieurs", 'Informatique', 'IA'], level: 'Formation', description: "CESI est une école d'ingénieurs et de management.", website: 'https://www.cesi.fr/', email: 'contact@cesi.fr' },
  { id: '32', name: 'INSA Blois', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=INSABlois', specialty: 'Institut National des Sciences Appliquées – Blois', location: 'Blois', address: '3 rue de la Chocolaterie, 41034 Blois', sectors: ['Formation', 'Recherche'], expertise: ['Ingénierie', 'IA appliquée', 'Recherche et formation'], level: 'Formation', description: "École d'ingénieurs de l'INSA Centre Val de Loire à Blois.", website: 'https://www.insa-centrevaldeloire.fr/fr/', email: 'adel.hafiane@insa-cvl.fr' },
  { id: '33', name: 'INSA Bourges', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=INSABourges', specialty: 'Institut National des Sciences Appliquées – Bourges', location: 'Bourges', address: '88 boulevard Lahitolle, 18022 Bourges', sectors: ['Formation', 'Recherche'], expertise: ['Ingénierie', 'Systèmes complexes', 'IA embarquée'], level: 'Formation', description: "École d'ingénieurs de l'INSA Centre Val de Loire à Bourges.", website: 'https://www.insa-centrevaldeloire.fr/fr/', email: 'adel.hafiane@insa-cvl.fr' },
  { id: '34', name: 'Université de Tours', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=UnivTours', specialty: 'Sciences & IA – Université de Tours', location: 'Tours', address: 'Avenue Monge, 37200 Tours', sectors: ['Formation', 'Recherche'], expertise: ['Sciences fondamentales', 'IA', 'Recherche'], level: 'Formation', description: "La faculté des sciences de l'Université de Tours.", website: 'https://sciences.univ-tours.fr/', email: 'scosciences@univ-tours.fr' },
  { id: '35', name: "Université d'Orléans", avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=UnivOrleans', specialty: 'Formation & Recherche en IA', location: 'Orléans', address: 'Château de la Source, 45100 Orléans', sectors: ['Formation', 'Recherche'], expertise: ['Formation universitaire', 'Recherche IA', 'Innovation'], level: 'Formation', description: "L'Université d'Orléans propose des formations et recherches en IA.", website: 'https://www.univ-orleans.fr/fr', email: 'doip@univ-orleans.fr' },
  { id: '36', name: 'MachineLearning.fr', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MachineLearningFR', specialty: 'Développement de logiciels & Machine Learning', location: 'Tours', address: '47 rue de la Mésangerie, 37540 Saint-Cyr-sur-Loire', sectors: ['Tech', 'Services'], expertise: ['Machine learning', 'Développement logiciel', 'IA sur-mesure'], level: 'Développement', description: "Entreprise spécialisée dans le développement de logiciels basés sur le machine learning.", website: 'https://machinelearning.fr/', email: 'jacqueline@machinelearning.fr' },
  { id: '37', name: 'Use Tech Lab', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=UseTechLab', specialty: 'Living lab Santé & Sciences Humaines', location: 'Tours', address: '49 boulevard Preuilly, 37000 Tours', sectors: ['Santé', 'Tech'], expertise: ['Santé numérique', 'Sciences humaines', 'Innovation sociétale'], level: 'Accompagnement', description: "Living lab en santé et sciences humaines et sociales.", website: 'https://www.usetechlab.com', email: 'clarisse.rabin@vyv3.fr' },
  { id: '38', name: 'Inetum', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Inetum', specialty: 'Services IT & Intelligence Artificielle', location: 'Orléans', address: "20 avenue des droits de l'Homme, 45000 Orléans", sectors: ['Tech', 'Services'], expertise: ['Services IT', 'Transformation digitale', 'IA entreprise'], level: 'Accompagnement', description: "Groupe de services numériques accompagnant les entreprises dans leur transformation digitale.", website: 'https://gfi.world/fr-fr/', email: 'jean.paul.muller@inetum.world' },
]

const news = [
  { id: 'n1', title: "5 entreprises de la région ont transformé leur production grâce à l'IA", category: 'Territoire', date: '2025-04-14', summary: "Portrait croisé de cinq PME et ETI du Centre-Val de Loire qui ont réussi leur virage IA.", readTime: 6, isHero: true },
  { id: 'n2', title: "Qu'est-ce que l'IA Act et pourquoi votre entreprise doit s'y préparer", category: 'Réglementation', date: '2025-04-10', summary: "Le règlement européen sur l'intelligence artificielle entre progressivement en vigueur.", readTime: 5 },
  { id: 'n3', title: "Mistral, GPT-4o, Gemini : quel LLM choisir pour votre entreprise en 2025 ?", category: 'Outils', date: '2025-04-07', summary: "Comparatif pratique des principaux modèles de langage disponibles pour les entreprises.", readTime: 7 },
  { id: 'n4', title: "La maintenance prédictive par IA s'impose dans l'industrie de la région", category: 'Industrie', date: '2025-04-03', summary: "Plusieurs fabricants d'Indre-et-Loire et du Cher ont adopté des solutions IA.", readTime: 4 },
  { id: 'n5', title: "IA générative : comment les équipes marketing s'en emparent", category: 'IA générative', date: '2025-03-28', summary: "Rédaction, image, vidéo, SEO... L'IA générative transforme les pratiques marketing.", readTime: 5 },
  { id: 'n6', title: "Open source et IA : la région soutient deux nouvelles initiatives", category: 'Innovation', date: '2025-03-24', summary: "La Région Centre-Val de Loire finance deux projets IA open source.", readTime: 3 },
  { id: 'n7', title: "Former ses équipes à l'IA : quels dispositifs existent en Centre-Val de Loire ?", category: 'Territoire', date: '2025-03-19', summary: "Tour d'horizon des aides et financements pour la montée en compétences IA.", readTime: 6 },
]

const trainings = [
  { id: 't1', title: "IA pour dirigeants : comprendre, décider, agir", provider: 'CCI Centre-Val de Loire', level: 'Débutant', format: 'Présentiel', profile: 'Dirigeants', objective: "Comprendre les enjeux et opportunités de l'IA.", duration: '1 journée', link: 'https://example.com' },
  { id: 't2', title: "Initiation à l'IA générative pour managers", provider: 'Digital Loire Valley', level: 'Débutant', format: 'En ligne', profile: 'Managers / Métiers', objective: "Découvrir les outils d'IA générative et identifier les cas d'usage.", duration: '3h en ligne', link: 'https://example.com' },
  { id: 't3', title: "Python & Machine Learning – Fondamentaux", provider: 'INSA Centre-Val de Loire', level: 'Intermédiaire', format: 'Mixte', profile: 'Profils techniques', objective: "Maîtriser les bases du machine learning avec Python.", duration: '3 jours', link: 'https://example.com' },
  { id: 't4', title: "IA et service public : enjeux et usages", provider: 'CNFPT', level: 'Débutant', format: 'En ligne', profile: 'Collectivités', objective: "Comprendre les applications de l'IA dans les collectivités.", duration: '2h en ligne', link: 'https://example.com' },
  { id: 't5', title: "Deep Learning & Réseaux de neurones", provider: 'Université de Tours', level: 'Avancé', format: 'Présentiel', profile: 'Profils techniques', objective: "Maîtriser les architectures de deep learning.", duration: '5 jours', link: 'https://example.com' },
  { id: 't6', title: "Automatiser ses processus avec l'IA – sans coder", provider: 'BPI Formation', level: 'Débutant', format: 'En ligne', profile: 'Managers / Métiers', objective: "Utiliser des outils no-code pour automatiser des tâches répétitives.", duration: '4h en ligne', link: 'https://example.com' },
  { id: 't7', title: "Stratégie data pour décideurs", provider: 'CCI Loire', level: 'Intermédiaire', format: 'Présentiel', profile: 'Dirigeants', objective: "Construire une stratégie data orientée valeur.", duration: '2 jours', link: 'https://example.com' },
  { id: 't8', title: "IA et marchés publics : ce que ça change", provider: 'ADGCF', level: 'Intermédiaire', format: 'Mixte', profile: 'Collectivités', objective: "Intégrer l'IA dans les achats et marchés publics.", duration: '1 journée', link: 'https://example.com' },
]

// ─── Import ────────────────────────────────────────────────────────────────────

async function importDocuments(type, items, transform) {
  console.log(`\n📦  Import ${type} (${items.length} docs)…`)
  for (const item of items) {
    const doc = { _type: type, ...transform(item) }
    await client.createOrReplace({ _id: `${type}-${item.id}`, ...doc })
    process.stdout.write('.')
  }
  console.log(' ✓')
}

await importDocuments('event', events, ({ id: _id, ...rest }) => rest)
await importDocuments('expert', experts, ({ id: _id, ...rest }) => rest)
await importDocuments('newsArticle', news, ({ id: _id, ...rest }) => rest)
await importDocuments('training', trainings, ({ id: _id, ...rest }) => rest)

console.log('\n✅  Migration terminée !')
